### ISSUE TITLE
[Todo] 이슈 1. 비디오 카드 컴포넌트 개발

### ISSUE THREAD

**Issue by Youjin-K** [JaeHye0k/Youtube-Clone#1]
# 비디오 카드 컴포넌트 구현

### 메인페이지 구현 계획 (이슈들)
이슈 1. 비디오 카드 컴포넌트 개발 - YouTube 메인 페이지에 표시될 비디오 카드 구현
이슈 2. 비디오 그리드 레이아웃 구현 - 반응형 레이아웃으로 구현
이슈 3. 카테고리 필터 구현 - 전체, 음악, 뉴스 ... 새로운 맞춤 동영상 등등(UI만 있을 예정)

## 이슈 1 - 비디오 카드 컴포넌트 개발: 세부 작업 내용
- [x] TypeScript 데이터 타입 정의
  - [x] 비디오 정보 (제목, 썸네일 URL, 조회수 등)
  - [x] 채널 정보 (이름, 프로필 이미지 등)
  - [x] API 응답 타입 (요청 성공 여부, 비디오 목록, 에러 메시지)

- [x] 비디오 카드 UI 컴포넌트 구현
  - [x] 썸네일 이미지 영역
  - [x] 채널 프로필 이미지
  - [x] 비디오 제목 (2줄 제한)
  - [x] 채널명
  - [x] 조회수와 업로드 시간

- [x] 인터랙션 효과 구현
  - [x] 샘플 비디오 파일 테스트(?)
  - [x] 반응형 비디오 그리드 호버 효과 구현

## 참고사항
- YouTube 실제 비디오 카드와 동일한 디자인으로 구현
- MSW를 사용한 API 연동 필요

**Comment by JaeHye0k** [comment]
작은 항목들도 체크박스로 변경해서 작업 완료할때마다 체크하시면 보기 더 편할 것 같아요!
