### ISSUE TITLE
[Todo] 이슈 2. 비디오 그리드 레이아웃 구현 - 반응형 레이아웃으로 구현

### ISSUE THREAD

**Issue by Youjin-K** [JaeHye0k/Youtube-Clone#14]
# 실제 비디오 데이터 연동 및 UX/UI 개선
-   [x] 실제 비디오 데이터 연동
     - [x] MSW를 활용해서 가짜 비디오 데이터 API 추가 (faker.js로 현실적인 데이터 생성)
     - [x] react-query로 데이터 페치 및 상태 관리
     - [x] 무한 스크롤 구현

-   [x] 메인 페이지 UI/UX 개선

       - [x] 로딩 상태 표시 (스켈레톤 UI)
       - [x] 조회수, 업로드 날짜 포맷팅 개선
     
-   [x] 영상 미리보기 
       - [x] 음소거 기능
       - [x] 영상 길이 표시 오버레이
       - [x] 영상 카드 호버 시 미리보기
       - [x] 자막 표시 기능
       - [x]  영상 길이 관련 시간 포맷팅 개선

## 작업 중인 파일명
- videos.api.ts(api)
- videoCard.tsx(Mainpage)
- useVideos.ts(hooks)
- browser.mock.ts(hooks)
- video.mock.ts(mock)
- Mainpage.tsx(pages)
- videoCard.styles.ts(style)
- mainPage.types.ts(types)
- fromat.ts(utills)
- 추가 파일 생성 시 입력 예정
