### ISSUE TITLE
[Todo] 헤더 작업

### ISSUE THREAD

**Issue by JaeHye0k** [JaeHye0k/Youtube-Clone#21]
## Todo
- 헤더 완성하기
    - [x] 검색 기능 (아무것도 입력 안했으면 검색 안 되도록하기)
    - [x] 드롭다운 기능
    - [x] 동영상 업로드 버튼 클릭 시 모달 창 띄우기
    - [x] 동영상 업로드 기능
    - [x] 반응형으로 제작
        - 검색창은 max-width: 656px에서 사라짐 
    - [x] 프로필 아이콘 클릭시 드롭다운 기능
