### ISSUE TITLE
[Todo]이슈 3. 메인페이지 카테고리 탭 구현 

### ISSUE THREAD

**Issue by Youjin-K** [JaeHye0k/Youtube-Clone#27]
## Todo

-   [x] 카테고리 추천 콘텐츠 섹션 구현- 전체, 음악, 뉴스 ... 새로운 맞춤 동영상 등등(UI만 있을 예정)
-   [x] 채널 페이지 이동 기능
-   [x] 더보기 UI 구현
-   [x] (필요할 경우) 비디오 카드 및 그리드 스타일 디테일 수정

## 피드백
-  [x] 첫 화면에 썸네일 화면 필요...
-  [x] 사이드 바 열고 닫을 때 비디오 카드들 함께 움직이도록 수정 필요
-  [x] 무한 스크롤이 안됨...

## 파일 구조 
- 파일 구조 헷갈릴 땐 미리 `이슈 - 제안`에 올려서 상의하도록 하겠습니다.
